// lib/records.ts — all 21 watch records and 8 timeline milestones.
// Ported from design_handoff_eot_archive/prototype/data.jsx.
//
// Movement and case numbers use the typographic apostrophe (U+2019).
// Ligne marks use three ASCII apostrophes (''') — IBM Plex Mono lacks the Unicode triple prime.
//
// TODO: The `photos` arrays contain filenames of unlicensed catalogue captures
// sourced from auction houses and the Huber & Banbery reference plates.
// See LICENSING.md for the full inventory. Do NOT deploy without licensed substitutes.

import type { WatchRecord, TimelineEntry } from './types';

export const RECORDS: WatchRecord[] = [
  // ── 19th century, archival ──────────────────────────────────────────────
  {
    slug: '24919',
    movement: '24’919',
    case: null,
    ref: null,
    mnfctYear: 1865,
    yearSold: 1865,
    caseMetal: "20''' pocket watch",
    title: '24’919 — 1865',
    knownFrom: 'Archival photograph / published reference',
    lastSaleHouse: null,
    priceRealizedUSD: null,
    notes: "20'''; sold to Peña, Madrid on 31 May 1865; equation table printed on the back. Photographs date from 1865.",
    hb: 'Huber & Banbery, image 175.',
    photos: ['24919_1.jpeg', '24919_2.jpeg'],
    imgKind: 'archival',
    complications: [
      { kind: 'eot', label: 'Equation of Time' },
      { kind: 'eot', label: 'Equation Table' },
    ],
    links: [],
    provenance: [
      { year: 1865, kind: 'manufacture', text: 'Manufactured; sold to Peña, Madrid (31 May).' },
    ],
    note: 'The earliest known Patek Philippe pocket watch incorporating an equation of time mechanism.',
  },
  {
    slug: '24920',
    movement: '24’920',
    case: null,
    ref: null,
    mnfctYear: 1867,
    yearSold: null,
    caseMetal: "20''' pocket watch",
    title: '24’920 — 1867',
    knownFrom: 'Archival photograph / published reference',
    lastSaleHouse: null,
    priceRealizedUSD: null,
    notes: "20'''; exhibited in Paris in 1867; small equation sector. Equation of time table and compass on the back. Photographs date from 1867.",
    hb: 'Huber & Banbery, image 176 (p. 203).',
    photos: ['24920_1.jpeg', '24920_2.jpeg'],
    imgKind: 'archival',
    complications: [
      { kind: 'eot', label: 'Equation Sector' },
      { kind: 'eot', label: 'Equation Table' },
    ],
    links: [],
    provenance: [
      { year: 1867, kind: 'manufacture', text: 'Exhibited in Paris.' },
    ],
  },
  {
    slug: '27116',
    movement: '27’116',
    case: null,
    ref: null,
    mnfctYear: 1867,
    yearSold: 1867,
    caseMetal: "19''' pocket watch",
    title: '27’116 — 1867',
    knownFrom: 'Archival photograph / published reference',
    lastSaleHouse: null,
    priceRealizedUSD: null,
    notes: "19'''; sold to Peña, Madrid in 1867; equation sector. Photographs date from 1867.",
    hb: 'Huber & Banbery, image 181.',
    photos: ['27116_1.jpeg', '27116_2.jpeg'],
    imgKind: 'archival',
    complications: [
      { kind: 'eot', label: 'Equation Sector' },
    ],
    links: [],
    provenance: [
      { year: 1867, kind: 'manufacture', text: 'Manufactured; sold to Peña, Madrid.' },
    ],
  },
  {
    slug: '31090',
    movement: '31’090',
    case: '31’090',
    ref: null,
    mnfctYear: 1868,
    yearSold: 1870,
    caseMetal: "20''' pocket watch",
    title: '31’090 — Rodanet, c. 1868–70',
    knownFrom: 'Public sale',
    lastSaleHouse: 'Cortrie Spezial Auktionen',
    priceRealizedUSD: 108058,
    notes: "20'''; made for A.H. Rodanet, Paris, circa 1868–70; case no. 31’090.",
    hb: null,
    photos: ['31090_1.png'],
    imgKind: 'auction',
    complications: [
      { kind: 'eot', label: 'Equation of Time' },
    ],
    links: [
      { year: 2019, label: 'Antiquorum, lot 382', href: 'https://catalog.antiquorum.swiss/en/lots/patek-philippe-made-for-a-h-rodanet-constructeur-de-chronometres-paris-no-9-294-lot-323-382' },
      { year: 2020, label: 'Cortrie, lot 4256', href: 'https://www.invaluable.com/auction-lot/pocket-watch-patek-philippe-pocket-chronometer-wi-4256-c-a3345b2851' },
      { year: 2020, label: 'Barnebys feature', href: 'https://www.barnebys.de/blog/ein-uhrahn-der-teuersten-taschenuhr-bei-cortrie' },
    ],
    provenance: [
      { year: 1868, kind: 'manufacture', text: 'Manufactured for A.H. Rodanet, Paris.' },
      { year: 1870, kind: 'retail', text: 'Delivered.' },
      { year: 2019, kind: 'auction', text: 'Antiquorum, lot 382 (27 October).' },
      { year: 2020, kind: 'auction', text: 'Cortrie Spezial Auktionen, lot 4256 (13 June).', price: 'EUR 80,000' },
    ],
  },
  {
    slug: '47887',
    movement: '47’887',
    case: null,
    ref: null,
    mnfctYear: 1874,
    yearSold: 1879,
    caseMetal: "19''' pocket watch",
    title: '47’887 — 1874',
    knownFrom: 'Published reference',
    lastSaleHouse: null,
    priceRealizedUSD: null,
    notes: "19'''; sold on 20 February 1879; small equation sector concentric to moon phases.",
    hb: 'Huber & Banbery, image 215.',
    photos: ['47887_1.jpeg', '47887_2.jpeg'],
    imgKind: 'archival',
    complications: [
      { kind: 'eot', label: 'Equation Sector' },
      { kind: 'mp', label: 'Moon Phase' },
    ],
    links: [],
    provenance: [
      { year: 1874, kind: 'manufacture', text: 'Manufactured.' },
      { year: 1879, kind: 'retail', text: 'Sold (20 February).' },
    ],
  },
  {
    slug: '80772',
    movement: '80’772',
    case: '215’215',
    ref: null,
    mnfctYear: 1890,
    yearSold: 1903,
    caseMetal: "19''' pocket watch",
    title: '80’772 — 1890',
    knownFrom: 'Public sale',
    lastSaleHouse: 'Christie’s',
    priceRealizedUSD: 527345,
    notes: "19'''; manufactured 1890, sold 1903; case no. 215’215.",
    hb: null,
    photos: ['80772_1.jpeg'],
    imgKind: 'auction',
    complications: [
      { kind: 'eot', label: 'Equation of Time' },
      { kind: 'mp', label: 'Moon Phase' },
    ],
    links: [
      { year: 1998, label: 'Antiquorum, lot 479', href: 'https://catalog.antiquorum.swiss/en/lots/patek-philippe-lot-92-479' },
      { year: 2002, label: 'Antiquorum, lot 208', href: 'https://catalog.antiquorum.swiss/en/lots/patek-philippe-lot-29-208' },
      { year: 2021, label: 'Christie’s, lot 208', href: 'https://www.christies.com/en/lot/lot-6316285' },
    ],
    provenance: [
      { year: 1890, kind: 'manufacture', text: 'Manufactured.' },
      { year: 1903, kind: 'retail', text: 'Sold.' },
      { year: 1998, kind: 'auction', text: 'Antiquorum, lot 479 (15 December).' },
      { year: 2002, kind: 'auction', text: 'Antiquorum, lot 208 (9 June).' },
      { year: 2021, kind: 'auction', text: 'Christie’s, lot 208 (9 May).', price: 'USD 527,345' },
    ],
  },
  {
    slug: '111505',
    movement: '111’505',
    case: null,
    ref: null,
    mnfctYear: 1898,
    yearSold: 1916,
    caseMetal: "20''' pocket watch",
    title: '111’505 — Mrs Bradford, 1898',
    knownFrom: 'Museum / institutional collection',
    lastSaleHouse: null,
    priceRealizedUSD: null,
    notes: "20'''; sold to Mrs Bradford; manufactured 1898. In the Beyer Museum, Zürich.",
    hb: 'Huber & Banbery, image 173.',
    photos: ['111505_1.jpeg', '111505_2.jpeg', '111505_3.jpeg', '111505_4.jpeg'],
    imgKind: 'archival',
    complications: [
      { kind: 'eot', label: 'Equation of Time' },
      { kind: 'mp', label: 'Moon Phase' },
    ],
    links: [],
    provenance: [
      { year: 1898, kind: 'manufacture', text: 'Manufactured.' },
      { year: 1916, kind: 'retail', text: 'Sold to Mrs Bradford.' },
      { year: null, kind: 'private', text: 'Beyer Museum, Zürich.' },
    ],
  },

  // ── Early 20th century — Packard & Graves ────────────────────────────────
  {
    slug: '198023',
    movement: '198’023',
    case: null,
    ref: null,
    mnfctYear: 1925,
    yearSold: 1927,
    caseMetal: "19''' pocket watch",
    title: '198’023 — James Ward Packard, 1925',
    knownFrom: 'Museum / institutional collection',
    lastSaleHouse: null,
    priceRealizedUSD: null,
    notes: "19'''; made for James Ward Packard. Patek Philippe’s most complicated watch until the Graves supercomplication. Formerly in the Smithsonian collection.",
    hb: 'Huber & Banbery, image 206.',
    photos: ['198023_1.jpeg', '198023_2.jpeg', '198023_3.jpeg', '198023_4.jpeg'],
    imgKind: 'archival',
    complications: [
      { kind: 'eot', label: 'Equation of Time' },
      { kind: 'pc', label: 'Perpetual Calendar' },
      { kind: 'mp', label: 'Moon Phase' },
      { kind: 'rep', label: 'Minute Repeater' },
      { kind: 'sid', label: 'Sky Chart' },
    ],
    links: [
      { year: null, label: 'TimeZone forum thread', href: 'https://forums.timezone.com/index.php?t=msg&th=503112&rid=0' },
    ],
    provenance: [
      { year: 1925, kind: 'manufacture', text: 'Manufactured for James Ward Packard.' },
      { year: 1927, kind: 'retail', text: 'Delivered.' },
      { year: null, kind: 'private', text: 'Formerly in the Smithsonian collection.' },
    ],
  },
  {
    slug: '198385',
    movement: '198’385',
    case: '416’769',
    ref: null,
    mnfctYear: 1925,
    yearSold: 1933,
    caseMetal: "25''' pocket watch",
    title: '198’385 — Henry Graves Jr., 1925–33',
    knownFrom: 'Public sale',
    lastSaleHouse: 'Sotheby’s',
    priceRealizedUSD: 24092122,
    notes: "25'''; manufacture began 1925, delivered 1933 to Henry Graves Jr.; case no. 416’769. Sold December 1999 for USD 11,000,000; sold at Sotheby’s Geneva, 11 November 2014, for USD 24,092,122.",
    hb: 'Huber & Banbery, image 232.',
    photos: ['198385_1.png', '198385_2.jpeg', '198385_3.jpeg'],
    imgKind: 'auction',
    complications: [
      { kind: 'eot', label: 'Equation of Time' },
      { kind: 'pc', label: 'Perpetual Calendar' },
      { kind: 'mp', label: 'Moon Phase' },
      { kind: 'rep', label: 'Minute Repeater' },
      { kind: 'sid', label: 'Sky Chart' },
      { kind: 'sid', label: 'Sidereal Time' },
      { kind: 'h24', label: '24-Hour Indication' },
      { kind: 'rep', label: 'Tourbillon' },
    ],
    links: [
      { year: 2014, label: 'Sotheby’s, lot 345', href: 'https://www.sothebys.com/en/auctions/ecatalogue/2014/important-watches-ge1404/lot.345.html' },
    ],
    provenance: [
      { year: 1925, kind: 'manufacture', text: 'Manufacture begins; commissioned by Henry Graves Jr.' },
      { year: 1933, kind: 'retail', text: 'Delivered to Henry Graves Jr.' },
      { year: 1999, kind: 'auction', text: 'Sold privately (December).', price: 'USD 11,000,000' },
      { year: 2014, kind: 'auction', text: 'Sotheby’s Geneva, lot 345 (11 November).', price: 'USD 24,092,122' },
    ],
  },

  // ── Calibre 89 (ref. 989), 1980 — four examples ─────────────────────────
  {
    slug: '844400',
    movement: '844’400',
    case: '2’839’425',
    ref: '989',
    mnfctYear: 1980,
    yearSold: 1989,
    caseMetal: 'Yellow gold',
    title: '844’400 — ‘Calibre 89’, yellow gold',
    knownFrom: 'Public sale',
    lastSaleHouse: 'Antiquorum',
    priceRealizedUSD: 5048313,
    notes: "Yellow gold Calibre 89. Sold Antiquorum, 9 April 1989, lot 301; Antiquorum, November 2009, lot 364; Sotheby’s, 14 May 2017.",
    hb: null,
    photos: ['844400_1.jpeg'],
    imgKind: 'auction',
    complications: [
      { kind: 'eot', label: 'Equation of Time' },
      { kind: 'pc', label: 'Perpetual Calendar' },
      { kind: 'mp', label: 'Moon Phase' },
      { kind: 'rep', label: 'Minute Repeater' },
      { kind: 'sid', label: 'Sidereal Time' },
      { kind: 'sid', label: 'Sky Chart' },
      { kind: 'h24', label: '24-Hour Indication' },
      { kind: 'rep', label: 'Tourbillon' },
    ],
    links: [
      { year: 1989, label: 'Antiquorum, lot 301', href: 'https://catalog.antiquorum.swiss/en/lots/lot-183-301?browse_all=1&page=3&q=calibre+89' },
      { year: 2009, label: 'Antiquorum, lot 364', href: 'https://catalog.antiquorum.swiss/en/lots/patek-philippe-lot-222-364?browse_all=1&page=3&q=calibre+89' },
      { year: 2017, label: 'Sotheby’s, lot 171', href: 'https://www.sothebys.com/en/auctions/ecatalogue/2017/important-watches-ge1701/lot.171.html' },
    ],
    provenance: [
      { year: 1980, kind: 'manufacture', text: 'Calibre 89 project begins (commemorating Patek Philippe’s 150th anniversary).' },
      { year: 1989, kind: 'auction', text: 'Antiquorum, lot 301 (9 April).', price: 'USD 5,048,313' },
      { year: 2009, kind: 'auction', text: 'Antiquorum, lot 364 (November).' },
      { year: 2017, kind: 'auction', text: 'Sotheby’s, lot 171 (14 May).' },
    ],
  },
  {
    slug: 'c89-wg',
    movement: null,
    case: null,
    ref: '989',
    mnfctYear: 1980,
    yearSold: 1989,
    caseMetal: 'White gold',
    title: '‘Calibre 89’ — white gold',
    knownFrom: 'Public sale',
    lastSaleHouse: 'Antiquorum',
    priceRealizedUSD: 5028556,
    notes: 'White gold Calibre 89. Sold Antiquorum, April 2004, lot 301.',
    hb: null,
    photos: ['c89-white-gold-calibre-r15_1.jpeg'],
    imgKind: 'auction',
    complications: [
      { kind: 'eot', label: 'Equation of Time' },
      { kind: 'pc', label: 'Perpetual Calendar' },
      { kind: 'mp', label: 'Moon Phase' },
      { kind: 'rep', label: 'Minute Repeater' },
      { kind: 'sid', label: 'Sidereal Time' },
      { kind: 'sid', label: 'Sky Chart' },
      { kind: 'h24', label: '24-Hour Indication' },
      { kind: 'rep', label: 'Tourbillon' },
    ],
    links: [
      { year: 2004, label: 'Antiquorum, lot 301', href: 'https://catalog.antiquorum.swiss/en/lots/patek-philippe-lot-51-301?browse_all=1&page=3&q=calibre+89' },
    ],
    provenance: [
      { year: 1980, kind: 'manufacture', text: 'Calibre 89 project.' },
      { year: 2004, kind: 'auction', text: 'Antiquorum, lot 301 (April).', price: 'USD 5,028,556' },
    ],
  },
  {
    slug: 'c89-pg',
    movement: null,
    case: null,
    ref: '989',
    mnfctYear: 1980,
    yearSold: 1989,
    caseMetal: 'Pink gold',
    title: '‘Calibre 89’ — pink gold',
    knownFrom: 'Reported private collection',
    lastSaleHouse: null,
    priceRealizedUSD: null,
    notes: 'Pink gold Calibre 89, purchased by an Italian collector.',
    hb: null,
    photos: [],
    imgKind: 'archival',
    complications: [
      { kind: 'eot', label: 'Equation of Time' },
      { kind: 'pc', label: 'Perpetual Calendar' },
      { kind: 'mp', label: 'Moon Phase' },
      { kind: 'rep', label: 'Minute Repeater' },
      { kind: 'sid', label: 'Sidereal Time' },
      { kind: 'sid', label: 'Sky Chart' },
      { kind: 'h24', label: '24-Hour Indication' },
      { kind: 'rep', label: 'Tourbillon' },
    ],
    links: [],
    provenance: [
      { year: 1980, kind: 'manufacture', text: 'Calibre 89 project.' },
      { year: null, kind: 'private', text: 'Reported in an Italian private collection.' },
    ],
  },
  {
    slug: 'c89-plat',
    movement: null,
    case: null,
    ref: '989',
    mnfctYear: 1980,
    yearSold: 1989,
    caseMetal: 'Platinum',
    title: '‘Calibre 89’ — platinum',
    knownFrom: 'Reported private collection',
    lastSaleHouse: null,
    priceRealizedUSD: null,
    notes: 'Platinum Calibre 89, purchased by a Middle-Eastern royal family.',
    hb: null,
    photos: [],
    imgKind: 'archival',
    complications: [
      { kind: 'eot', label: 'Equation of Time' },
      { kind: 'pc', label: 'Perpetual Calendar' },
      { kind: 'mp', label: 'Moon Phase' },
      { kind: 'rep', label: 'Minute Repeater' },
      { kind: 'sid', label: 'Sidereal Time' },
      { kind: 'sid', label: 'Sky Chart' },
      { kind: 'h24', label: '24-Hour Indication' },
      { kind: 'rep', label: 'Tourbillon' },
    ],
    links: [],
    provenance: [
      { year: 1980, kind: 'manufacture', text: 'Calibre 89 project.' },
      { year: null, kind: 'private', text: 'Reported in a Middle-Eastern royal collection.' },
    ],
  },

  // ── References 880/1, 962/1, 881/1, 990/1 ───────────────────────────────
  {
    slug: '866569',
    movement: '866’569',
    case: '332’912',
    ref: '880/1',
    mnfctYear: 1974,
    yearSold: 1980,
    caseMetal: 'Open-face, double-signed Beyer',
    title: '866’569 — Reference 880/1',
    knownFrom: 'Public sale',
    lastSaleHouse: 'Christie’s',
    priceRealizedUSD: 152653,
    notes: "19''' / 17'''; made for Beyer, Zürich, 1974, sold 1980. The only reference 880 with equation of time. Double-signed Beyer.",
    hb: null,
    photos: ['866569_1.jpeg'],
    imgKind: 'auction',
    complications: [
      { kind: 'eot', label: 'Equation of Time' },
      { kind: 'pc', label: 'Perpetual Calendar' },
      { kind: 'mp', label: 'Moon Phase' },
      { kind: 'rep', label: 'Minute Repeater' },
    ],
    links: [
      { year: 2001, label: 'Christie’s, lot 25', href: 'https://www.christies.com/lot/lot-3814506?ldp_breadcrumb=back&intObjectID=3814506&from=salessummary&lid=1' },
      { year: 2002, label: 'Antiquorum, ref. 880', href: 'https://catalog.antiquorum.swiss/en/lots/patek-philippe-ref-ref-880-lot-29-210' },
      { year: 2021, label: 'Christie’s, lot 208', href: 'https://www.christies.com/lot/lot-6316284' },
    ],
    provenance: [
      { year: 1974, kind: 'manufacture', text: 'Manufactured for Beyer, Zürich.' },
      { year: 1980, kind: 'retail', text: 'Sold by Beyer.' },
      { year: 2001, kind: 'auction', text: 'Christie’s, lot 25 (13 November).' },
      { year: 2002, kind: 'auction', text: 'Antiquorum (8 June).' },
      { year: 2021, kind: 'auction', text: 'Christie’s, lot 208 (9 May).', price: 'USD 152,653' },
    ],
  },
  {
    slug: '866590',
    movement: '866’590',
    case: null,
    ref: '962/1',
    mnfctYear: 1992,
    yearSold: null,
    caseMetal: "17''' open-face",
    title: '866’590 — Reference 962/1',
    knownFrom: 'Catalogue / published reference',
    lastSaleHouse: null,
    priceRealizedUSD: null,
    notes: "17'''; listed in the Patek Philippe catalogue for 1993; ref. 962/1.",
    hb: null,
    photos: ['866590_1.jpeg'],
    imgKind: 'archival',
    complications: [
      { kind: 'eot', label: 'Equation of Time' },
      { kind: 'pc', label: 'Perpetual Calendar' },
      { kind: 'mp', label: 'Moon Phase' },
      { kind: 'rep', label: 'Minute Repeater' },
      { kind: 'h24', label: '24-Hour Indication' },
    ],
    links: [
      { year: 2019, label: 'Dobiaschofsky mention', href: 'https://www.dobiaschofsky.com/d110-A129-13058.html' },
    ],
    provenance: [
      { year: 1992, kind: 'manufacture', text: 'Manufactured.' },
      { year: 1993, kind: 'private', text: 'Listed in Patek Philippe catalogue.' },
    ],
  },
  {
    slug: '866592',
    movement: '866’592',
    case: '2’835’217',
    ref: '962/1',
    mnfctYear: 1992,
    yearSold: 1999,
    caseMetal: "Yellow gold, 17'''",
    title: '866’592 — Reference 962/1',
    knownFrom: 'Public sale',
    lastSaleHouse: 'Dobiaschofsky',
    priceRealizedUSD: 70371,
    notes: "17'''; manufactured 1992, sold by Gübelin (Lucerne) 1999; sold Dobiaschofsky 2019; sold 2ToneVintage 2022; ref. 962/1.",
    hb: null,
    photos: ['866592_1.jpeg'],
    imgKind: 'auction',
    complications: [
      { kind: 'eot', label: 'Equation of Time' },
      { kind: 'pc', label: 'Perpetual Calendar' },
      { kind: 'mp', label: 'Moon Phase' },
      { kind: 'rep', label: 'Minute Repeater' },
      { kind: 'h24', label: '24-Hour Indication' },
    ],
    links: [
      { year: 2019, label: 'Dobiaschofsky listing', href: 'https://www.dobiaschofsky.com/d110-A129-13058.html' },
      { year: 2022, label: '2ToneVintage listing', href: 'https://www.2tonevintage.com/product/patek-philippe-ref-962-1j-rq-e-9-hands-grande-complication-pocket-watch/' },
    ],
    provenance: [
      { year: 1992, kind: 'manufacture', text: "Manufactured. 17''' calibre." },
      { year: 1999, kind: 'retail', text: 'Sold by Gübelin (Lucerne).' },
      { year: 2019, kind: 'auction', text: 'Dobiaschofsky public sale.', price: 'USD 70,371' },
      { year: 2022, kind: 'private', text: 'Sold by 2ToneVintage.' },
    ],
  },
  {
    slug: '866595',
    movement: '866’595',
    case: '2’837’635',
    ref: '962/1',
    mnfctYear: 1992,
    yearSold: 2001,
    caseMetal: "18k gold, 17''' open-face",
    title: '866’595 — Reference 962/1',
    knownFrom: 'Public sale',
    lastSaleHouse: 'Bonhams',
    priceRealizedUSD: 191932,
    notes: "17'''; acquired January 2001 in Taiwan; case no. 2’837’635; sold Bonhams, 15 June 2022; ref. 962/1.",
    hb: null,
    photos: ['866595_1.jpeg'],
    imgKind: 'auction',
    complications: [
      { kind: 'eot', label: 'Equation of Time' },
      { kind: 'pc', label: 'Perpetual Calendar' },
      { kind: 'mp', label: 'Moon Phase' },
      { kind: 'rep', label: 'Minute Repeater' },
      { kind: 'h24', label: '24-Hour Indication' },
    ],
    links: [
      { year: 2022, label: 'Bonhams, lot 35', href: 'https://www.bonhams.com/auction/27662/lot/35/patek-philippe-an-extremely-fine-and-very-rare-18k-gold-keyless-wind-open-face-minute-repeating-perpetual-calendar-pocket-watch-with-moon-phase-and-24-hour-indication-ref-9621j-001-purchased-january-2001/' },
    ],
    provenance: [
      { year: 1992, kind: 'manufacture', text: 'Manufactured.' },
      { year: 2001, kind: 'retail', text: 'Acquired in Taiwan (January).' },
      { year: 2022, kind: 'auction', text: 'Bonhams, lot 35 (15 June).', price: 'USD 191,932' },
    ],
  },
  {
    slug: '866713',
    movement: '866’713',
    case: '332’925',
    ref: '881/1',
    mnfctYear: 1983,
    yearSold: 1983,
    caseMetal: 'Hunter case',
    title: '866’713 — Reference 881/1',
    knownFrom: 'Public sale',
    lastSaleHouse: 'Phillips',
    priceRealizedUSD: 165106,
    notes: "17''', 29 jewels; made for Beyer, Zürich, 1983, sold 1983; case no. 332’925; hunter case. One of four watches made for Beyer in the early 1980s.",
    hb: null,
    photos: ['866713_1.jpeg'],
    imgKind: 'auction',
    complications: [
      { kind: 'eot', label: 'Equation of Time' },
      { kind: 'pc', label: 'Perpetual Calendar' },
      { kind: 'mp', label: 'Moon Phase' },
      { kind: 'rep', label: 'Minute Repeater' },
    ],
    links: [
      { year: 2003, label: 'Christie’s lot', href: 'https://www.christies.com/lot/lot-4180731?ldp_breadcrumb=back&intObjectID=4180731&from=salessummary&lid=1' },
      { year: 2016, label: 'Phillips, lot 176', href: 'https://www.phillips.com/detail/patek-philippe/CH080116/176' },
    ],
    provenance: [
      { year: 1983, kind: 'manufacture', text: 'Manufactured for Beyer, Zürich.' },
      { year: 1983, kind: 'retail', text: 'Sold by Beyer.' },
      { year: 2003, kind: 'auction', text: 'Christie’s (17 November).' },
      { year: 2016, kind: 'auction', text: 'Phillips, lot 176 (15 May).', price: 'USD 165,106' },
    ],
  },
  {
    slug: '866714',
    movement: '866’714',
    case: '332’926',
    ref: '881/1',
    mnfctYear: 1982,
    yearSold: 1982,
    caseMetal: 'Yellow gold, hunter case',
    title: '866’714 — Reference 881/1',
    knownFrom: 'Public sale',
    lastSaleHouse: 'Sotheby’s',
    priceRealizedUSD: 154440,
    notes: "17'''; sold to Beyer, Zürich, 1982; case no. 332’926; hunter case.",
    hb: null,
    photos: ['866714_1.jpeg'],
    imgKind: 'auction',
    complications: [
      { kind: 'eot', label: 'Equation of Time' },
      { kind: 'pc', label: 'Perpetual Calendar' },
      { kind: 'mp', label: 'Moon Phase' },
      { kind: 'rep', label: 'Minute Repeater' },
    ],
    links: [
      { year: 1989, label: 'Antiquorum, lot 253', href: 'https://catalog.antiquorum.swiss/en/lots/patek-philippe-ref-ref-881-lot-183-253?browse_all=1&page=1&q=patek+866714' },
      { year: 2004, label: 'Christie’s lot', href: 'https://www.christies.com/lot/lot-4304728' },
      { year: 2024, label: 'Sotheby’s, ref. 881/001', href: 'https://www.sothebys.com/en/buy/auction/2024/important-watches-i-2/reference-881-001-a-yellow-gold-hunting-case' },
    ],
    provenance: [
      { year: 1982, kind: 'manufacture', text: 'Manufactured for Beyer, Zürich.' },
      { year: 1982, kind: 'retail', text: 'Sold by Beyer.' },
      { year: 1989, kind: 'auction', text: 'Antiquorum, lot 253 (9 April).' },
      { year: 2004, kind: 'auction', text: 'Christie’s (10 June).' },
      { year: 2024, kind: 'auction', text: 'Sotheby’s (4 October).', price: 'USD 154,440' },
    ],
  },
  {
    slug: '866721',
    movement: '866’721',
    case: null,
    ref: '881/1',
    mnfctYear: 1982,
    yearSold: null,
    caseMetal: 'Engine-turned hunter case',
    title: '866’721 — Reference 881/1',
    knownFrom: 'Museum / institutional collection',
    lastSaleHouse: null,
    priceRealizedUSD: null,
    notes: "17'''; sold through Beyer to a Swiss client in the 1980s; engine-turned hunter case; later donated to the Musée d’Horlogerie du Locle.",
    hb: null,
    photos: [],
    imgKind: 'archival',
    complications: [
      { kind: 'eot', label: 'Equation of Time' },
      { kind: 'pc', label: 'Perpetual Calendar' },
      { kind: 'mp', label: 'Moon Phase' },
      { kind: 'rep', label: 'Minute Repeater' },
    ],
    links: [
      { year: 2003, label: 'Christie’s mention', href: 'https://www.christies.com/lot/lot-4180731?ldp_breadcrumb=back&intObjectID=4180731&from=salessummary&lid=1' },
      { year: 2004, label: 'Christie’s mention', href: 'https://www.christies.com/lot/lot-4304728' },
    ],
    provenance: [
      { year: 1982, kind: 'manufacture', text: 'Manufactured for Beyer, Zürich.' },
      { year: null, kind: 'retail', text: 'Sold through Beyer to a Swiss client.' },
      { year: null, kind: 'private', text: 'Donated to the Musée d’Horlogerie du Locle.' },
    ],
  },
  {
    slug: '3200005',
    movement: '3’200’005',
    case: '4’125’166',
    ref: '990/1',
    mnfctYear: 2000,
    yearSold: 2008,
    caseMetal: 'Star Calibre 2000',
    title: '3’200’005 — Reference 990/1, Star Calibre 2000',
    knownFrom: 'Public sale',
    lastSaleHouse: 'Christie’s',
    priceRealizedUSD: 3263700,
    notes: 'Star Calibre 2000; case no. 4’125’166. One of twenty examples produced. Sold Christie’s, 28 November 2012.',
    hb: null,
    photos: ['3200005_1.jpeg'],
    imgKind: 'auction',
    complications: [
      { kind: 'eot', label: 'Equation of Time' },
      { kind: 'pc', label: 'Perpetual Calendar' },
      { kind: 'mp', label: 'Moon Phase' },
      { kind: 'rep', label: 'Minute Repeater' },
      { kind: 'sid', label: 'Sky Chart' },
      { kind: 'sid', label: 'Sidereal Time' },
      { kind: 'h24', label: '24-Hour Indication' },
      { kind: 'rep', label: 'Tourbillon' },
    ],
    links: [
      { year: 2012, label: 'Christie’s lot', href: 'https://www.christies.com/en/lot/lot-5638919' },
    ],
    provenance: [
      { year: 2000, kind: 'manufacture', text: 'Star Calibre 2000 produced (20 examples).' },
      { year: 2008, kind: 'retail', text: 'Sold.' },
      { year: 2012, kind: 'auction', text: 'Christie’s (28 November).', price: 'USD 3,263,700' },
    ],
  },
  {
    slug: 'sc2000-lot',
    movement: '3’200’017 / 3’200’018 / 3’200’019 / 3’200’020',
    case: '4’252’683 / 4’252’684 / 4’252’685 / 4’252’686',
    ref: '990/1',
    mnfctYear: 2000,
    yearSold: 2025,
    caseMetal: 'Star Calibre 2000',
    title: '3’200’017–020 — Four Star Calibre 2000, Sotheby’s 2025',
    knownFrom: 'Public sale',
    lastSaleHouse: 'Sotheby’s',
    priceRealizedUSD: 11910000,
    notes: 'Four Star Calibre 2000 examples (ref. 990/1) sold as a single lot at Sotheby’s, 5 December 2025. Movements 3’200’017, 3’200’018, 3’200’019, and 3’200’020; case nos. 4’252’683–4’252’686. Part of the 20-example limited production.',
    hb: null,
    photos: [],
    imgKind: 'auction',
    complications: [
      { kind: 'eot', label: 'Equation of Time' },
      { kind: 'pc', label: 'Perpetual Calendar' },
      { kind: 'mp', label: 'Moon Phase' },
      { kind: 'rep', label: 'Minute Repeater' },
      { kind: 'sid', label: 'Sky Chart' },
      { kind: 'sid', label: 'Sidereal Time' },
      { kind: 'h24', label: '24-Hour Indication' },
      { kind: 'rep', label: 'Tourbillon' },
    ],
    links: [
      { year: 2025, label: 'Sotheby’s, Watches & Jewels, Dec 2025', href: 'https://www.sothebys.com/en/buy/auction/2025/watches-jewels-ad2502' },
    ],
    provenance: [
      { year: 2000, kind: 'manufacture', text: 'Star Calibre 2000 produced (20 examples).' },
      { year: 2006, kind: 'retail', text: 'Delivered.' },
      { year: 2025, kind: 'auction', text: 'Sotheby’s, four watches sold as one lot (5 December).', price: 'USD 11,910,000' },
    ],
  },
];

// ── Timeline milestones (8 entries) ─────────────────────────────────────────

export const TIMELINE: TimelineEntry[] = [
  {
    year: 1865,
    key: true,
    title: "Movement 24’919 — the earliest known equation of time",
    desc: 'Sold to Peña, Madrid (31 May). The first equation of time complication recorded in the Patek Philippe register.',
  },
  {
    year: 1868,
    title: "Movement 31’090 — A.H. Rodanet",
    desc: 'Made for Parisian chronometer constructor A.H. Rodanet. Resurfaced at Antiquorum (2019) and Cortrie (2020).',
  },
  {
    year: 1890,
    title: "Movement 80’772 — moon phase pairing",
    desc: 'Made 1890, sold 1903. The complication enters its mature 19th-century form.',
  },
  {
    year: 1925,
    key: true,
    title: "Movement 198’023 — James Ward Packard",
    desc: "Patek Philippe’s most complicated watch until the Graves supercomplication. Equation of time, sky chart, perpetual calendar, minute repeater.",
  },
  {
    year: 1933,
    key: true,
    title: "Movement 198’385 — Henry Graves Jr. supercomplication",
    desc: 'Twenty-four complications including equation of time. Sold at Sotheby’s in 2014 for USD 23,237,000.',
  },
  {
    year: 1980,
    key: true,
    title: '‘Calibre 89’, reference 989 — four examples',
    desc: "Patek Philippe’s 150th anniversary watch. Thirty-three complications. Four examples manufactured between 1980 and 1989 in yellow gold, white gold, pink gold, and platinum.",
  },
  {
    year: 1992,
    key: true,
    title: "Reference 962/1 — modern grande complication",
    desc: "Three known examples (movements 866’590, 866’592, 866’595). Equation of time with perpetual calendar, moon phase, minute repeater, and 24-hour indication.",
  },
  {
    year: 2000,
    key: true,
    title: 'Reference 990/1 — Star Calibre 2000',
    desc: 'Twenty examples produced. Equation of time integrated with sky chart, sidereal time, perpetual calendar, minute repeater.',
  },
];

// ── Derived helpers ──────────────────────────────────────────────────────────

export function getRecord(slug: string): WatchRecord | undefined {
  return RECORDS.find((r) => r.slug === slug);
}

export const AUCTION_COUNT = RECORDS.filter((r) => r.priceRealizedUSD !== null).length;

export const YEAR_RANGE = '1865–2000';
